import { GoogleGenAI } from "@google/genai";
import { extractBase64Data } from '@/utils/geminiUtils';

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key not found");
  return new GoogleGenAI({ apiKey });
};

const MODEL_NAME = 'gemini-2.5-flash-image';

export const generateSticker = async (base64Image: string): Promise<string> => {
  const ai = getClient();
  const cleanBase64 = extractBase64Data(base64Image);

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Assuming PNG input or generic conversion
              data: cleanBase64,
            },
          },
          {
            text: "Create a high-quality die-cut sticker of the main subject in this image. The background must be solid white. The style should be vibrant, clean vector art or high-definition cutout style. Isolate the subject completely.",
          },
        ],
      },
      config: {
        // Gemini 2.5 Flash Image config
      }
    });

    // Extract image from response
    let resultImage = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          resultImage = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!resultImage) {
      throw new Error("No image generated by the model.");
    }

    return resultImage;

  } catch (error) {
    console.error("Sticker generation failed:", error);
    throw error;
  }
};

export const editSticker = async (base64Image: string, prompt: string): Promise<string> => {
  const ai = getClient();
  const cleanBase64 = extractBase64Data(base64Image);

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: cleanBase64,
            },
          },
          {
            text: `Edit this sticker image: ${prompt}. Maintain the white background and sticker aesthetic if possible.`,
          },
        ],
      },
    });

    let resultImage = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          resultImage = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!resultImage) {
        // Fallback: sometimes the model might output text explaining why it failed
        const textPart = response.candidates?.[0]?.content?.parts?.find(p => p.text);
        if (textPart) throw new Error(textPart.text);
        throw new Error("No image generated.");
    }

    return resultImage;
  } catch (error) {
    console.error("Edit failed:", error);
    throw error;
  }
};

export const generateAnimationFrames = async (
  base64Image: string, 
  instruction: string, 
  frameCount: number = 3
): Promise<string[]> => {
  const ai = getClient();
  const cleanBase64 = extractBase64Data(base64Image);
  const frames: string[] = [];

  // We will generate frames sequentially to try and maintain some coherence, 
  // or parallel with varied prompts. Parallel is faster for a demo.
  // For simple animations like "Wiggle", we can prompt for specific states.
  
  const prompts = [];
  if (instruction.includes('wiggle')) {
      prompts.push("Slightly tilt the subject to the left. Keep same style and white background.");
      prompts.push("Keep the subject centered. Keep same style and white background.");
      prompts.push("Slightly tilt the subject to the right. Keep same style and white background.");
  } else if (instruction.includes('pulse')) {
      prompts.push("Make the subject slightly smaller (90% size). Keep white background.");
      prompts.push("Keep the subject normal size. Keep white background.");
      prompts.push("Make the subject slightly larger (110% size). Keep white background.");
  } else {
      // Custom or generic
      for (let i = 0; i < frameCount; i++) {
        prompts.push(`Variation ${i+1}: ${instruction}. Keep the exact same style and white background.`);
      }
  }

  // Execute requests in parallel
  const promises = prompts.map(async (p) => {
    try {
      const response = await ai.models.generateContent({
        model: MODEL_NAME,
        contents: {
          parts: [
            { inlineData: { mimeType: 'image/png', data: cleanBase64 } },
            { text: `Generate a new frame for an animation based on this image. ${p}` },
          ],
        },
      });
      
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
      return null;
    } catch (e) {
      console.error("Frame generation error", e);
      return null;
    }
  });

  const results = await Promise.all(promises);
  results.forEach(res => {
    if (res) frames.push(res);
  });
  
  // To make a smooth loop for wiggle/pulse, we might want to order them: Left -> Center -> Right -> Center
  if (instruction.includes('wiggle') && frames.length === 3) {
      // Assuming promises returned in order (Promise.all preserves order)
      // [Left, Center, Right] -> [Left, Center, Right, Center] for smooth loop
      frames.push(frames[1]); 
  }

  return frames;
};
